# -*- coding: utf-8 -*-
"""Atm_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135dWtxebnSM7cDPmszn-fSd1KahhzFkn
"""

accounts = {}

def create_account():
    acc_no = input("Enter Account Number: ")
    if acc_no in accounts:
        print("Account already exists")
        return

    name = input("Enter Name: ")
    pin = input("Set PIN: ")
    balance = float(input("Enter Initial Balance: "))

    accounts[acc_no] = {
        "name": name,
        "pin": pin,
        "balance": balance,
        "transactions": []
    }

    print("Account Created Successfully")


def login():
    acc_no = input("Enter Account Number: ")
    pin = input("Enter PIN: ")

    if acc_no in accounts and accounts[acc_no]["pin"] == pin:
        print("Login Successful")
        menu(acc_no)
    else:
        print("Invalid Account Number or PIN")


def check_balance(acc_no):
    print("Available Balance:", accounts[acc_no]["balance"])


def deposit(acc_no):
    amount = float(input("Enter amount to deposit: "))
    accounts[acc_no]["balance"] += amount
    accounts[acc_no]["transactions"].append("Deposited " + str(amount))
    print("Deposit Successful")


def withdraw(acc_no):
    amount = float(input("Enter amount to withdraw: "))
    if amount <= accounts[acc_no]["balance"]:
        accounts[acc_no]["balance"] -= amount
        accounts[acc_no]["transactions"].append("Withdrawn " + str(amount))
        print("Please collect your cash")
    else:
        print("Insufficient Balance")


def transaction_history(acc_no):
    print("Transaction History:")
    for t in accounts[acc_no]["transactions"]:
        print(t)


def menu(acc_no):
    while True:
        print("\n1. Check Balance")
        print("2. Deposit")
        print("3. Withdraw")
        print("4. Transaction History")
        print("5. Logout")

        choice = input("Enter choice: ")

        if choice == "1":
            check_balance(acc_no)
        elif choice == "2":
            deposit(acc_no)
        elif choice == "3":
            withdraw(acc_no)
        elif choice == "4":
            transaction_history(acc_no)
        elif choice == "5":
            print("Logged Out")
            break
        else:
            print("Invalid Choice")


while True:
    print("\n====== ATM SYSTEM ======")
    print("1. Create Account")
    print("2. Login")
    print("3. Exit")

    main_choice = input("Enter choice: ")

    if main_choice == "1":
        create_account()
    elif main_choice == "2":
        login()
    elif main_choice == "3":
        print("Thank You")
        break
    else:
        print("Invalid Choice")